spring.application.name=enterpriseflow
spring.datasource.url=jdbc:postgresql://localhost:5432/enterprisedb
spring.datasource.username=postgres
spring.datasource.password=postgres
server.port=8001
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true
